jobs:
  include:
    - stage: build
      language: java
      jdk: openjdk8
      jdk: openjdk9      
      sudo: required
      script: mvn clean install dockerfile:build
      
    - stage: deploy    
      sudo: required
      script: docker run -d -t -p 8080:8080 alogo53/swagger-spring:1.0.0
      
stages:
  - build     
  - deploy
