jobs:
  include:
    - stage: build-deploy
      language: java
      jdk: openjdk8
      sudo: required
      script: 
        - mvn clean install dockerfile:build
        - docker run -d -t -p 8080:8080 alogo53/swagger-spring:1.0.0
      
    - stage: test    
      language: node_js
      node_js:
        - "8.2.1"
      install:
        - npm install newman
        before_script:
            - node --version
            - npm --version
            - node_modules/.bin/newman --version
        
      
stages:
  - build-deploy     
  - test
