sudo: required

services:
  - docker

language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - install:
        - npm install newman


before_install:
  - docker version
  - docker info

before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version  
    
script:
  - mvn clean install dockerfile:build
  - docker run -d -t -p 8080:8080 alogo53/swagger-spring:1.0.0
