sudo: required

services:
  - docker

language: java

matrix:
  include:
    - jdk: openjdk8
    #- jdk: openjdk9
    #- jdk: openjdk10


before_install:
  - docker version
  - docker info
  

install:
    - npm install newman

before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version  

    
script:
  - mvn clean install dockerfile:build
  - docker run --name example_api -d -t -p 127.0.0.1:8080:8080 alogo53/swagger-spring-example:1.0.0
  - docker ps
  - docker logs example_api
  - node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
  
  
after_script:
    - curl -v 127.0.0.1:8080
    - curl -v localhost:8080
    - docker ps
    - docker logs example_api
