sudo: required
services:
- docker
language: java
matrix:
  include:
  - jdk: openjdk8
before_install:
- docker version
- docker info
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- mvn clean install dockerfile:build
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 alogo53/swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- echo $MY_SECRET_ENV
- printenv
env:
  matrix:
    secure: Vsgm5dAIRwnWn/xKB+FPigpXoTkDlHJ1M+uI1Nl5NSQcnU8JOm7PFpncBCe3IuGsLuftI37VJox7T4GykWTj4C9WjqzipgK1G5xLrqvO8liSMsJ3gkE6gpTy0V+wNSiAudKYIHY10PsuuYaXtBXZXNfEgb7h8/+fcZ70jWewMRkJr8O9YFkiWivxEeJd1J6FJyUh0kwFCRJjZgy/6Sl1DlTwsoSLmLq8eJe9O0zDwKvCyot3kr5MGVnJcoOgNoFql1bambSvLJtDcFdxZIaRp8POV2kOx6wGMgTMNFSURfbrp//kmEmsXtxUIj0z+kwKuzsL+Jj4NuxHEGEDKss4l1Vn250pvXcmVRkojThLJxWZ3mBrAtbR1loi9KCd+wkFpk09pc+6HyhQ1onr4NTc5u0xbpADYGS2LipZgFy3JGVjAStDOO35kiw21Xe4YA4bHz+/sEeSnoU0lqNo3Dzf6S0gAr1W1MipQ1fUqIoxXiMWrZc2fa9ouoz2F/DphHAGdR6LjA6i/vypKTcwYwycnwbWqeyWAnzf6+PhBmFxCOAACCV0dek+aN2IjP3N5KFHwt0fSsBJFm/Iw9fK0K8wGW+zOENwC/+8FwOv9gBdLxvfDxW0cAN7Xd6SGsYJF+1hv+Hubtn8wHYflIZX2sTLmONBZg6lLadYXFCvMsFP0Yk=
