sudo: required
services:
- docker
language: java
matrix:
  include:
  - jdk: openjdk8
before_install:
- docker version
- docker info
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- mvn clean install dockerfile:build
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 alogo53/swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag alogo53/swagger-spring-example:1.0.0 alogo53/swagger-spring-example:1.0.0
- docker push alogo53/swagger-spring-example:1.0.0
env:
  matrix:
  - secure: T/vRtKJTQBisDytCY7W08kIweRWv3MJg00vJ/C1kR56jqLati9q56jjAfoR6ZB3ec6E9m1qeMB3xq28IEN86zgANopeas5/uyAWOj+VDanVJrlCmTAnDVRAaZ0CUPlwxpufyYL6fxhpQrpm30IdrP6fXb0SGyPDASJnHcJa1AZoLRHWaYlTKFcMyY5IPLsH16lNvJ3ul94MqgTlsnlnXTv84BXJwwIep/dHBJuQnDMBxwgYwlVshB1rOFwl0RarS5n3jVI9u8Kr+kCABfAo/IBxAG654GGvsGqW+WWnT2ARA28zTlwJ5D0vE8Zpz24eNPEr6xQgX3BjGqrIS0jvMgFSK/BJ2h0Lj+UCU29tbroCBtaTXcCXcf+J5N04ik0XMgJnDvehg9NRtXhv2vSrUzQNnOTITE7ZeTKmi3o5snUnkDSe6Ca0iQf5qrc4BTF/sAcEfUSIb/95NTpYqHBP7xID3kxm+lZb5l5yVFsEYo+jLNFFYqbFdtSiR+d9lMVar/iSexgO/c7EUOmHeJ1aqUqaWdQSpfCdBCjXflkhZr6sCIfmzML5Zq2veFmbIuKnMUBtQDxkIYS6BBSQ7OvFdxodKegQaE0cgNzyHP3vJadGuB30+shNON9JtWr4xvjlglNpr+fcDQIYV5CM+15ZUOGo1w1y7lXNB1MevIEOOQ2U=
  - secure: aI4sKD7P/N55r5KmMTESXL8cfdajLOr4hErEOWYymBetzcf1cYglAYMeiKcfK+oJkDoG0okUL/05xJdEUmBh+Eap0Znb3J33toZ/MQPQJWUJ6IcYq2zZFO/Cd5Bkc609S2UmaWObs30MtYhcT4G6pwY4i/jKAeZnxmVy3qKBn6Z8Qjddh/5ncQ3LaqgFXe6/bmOHwhXx5alDyT0Q0H2mo73Zy8n0kJZMRjDl83PiNB0aPmh9HDw1SDF0ayw9LGjolHZ0efnAgT1zPNKvzEIq6TIHSxjZskEgOn1uqE/Zt67OOdzKs+ColkwvDis37fHJIzZDg3ehaAOU+NmR7q+tQPB6va6OkUUOeviPrfix0njN/DRcBEHmmE5GgEZQbsA4XnWaWTWf/REmvVfIRfScFKr+hV/YGNGvTAqYHFqbGvBTm5Xi5cKqBiY5wq6wTKd3+N9GiW9oR5aCkeyAsZ6b707dmuDF50EXrWDFz66+UTfiu/gwkIILBKP8qkvnWWYri8/g/D7VTaYESCTHaMAx0WOV8dQ7wLKKHsfPnrlbnamriLM+Rgx8vGKVIXRKNaNP1aEST7eiBVPRRHJZN0TkfW1QDeBjn2zjpBRUpfaTk6XivizFXf/XKjld4kFSkW/3gktLMtywOVxbL6U1J2mHR5euVy42a90lVd3qc9zlpB4=
