sudo: required
services:
  - docker
language: java
env:
  global:
    - secure:"PWmDuZcCzbVkkVRc4CTVzRh6VqaBc+Q3nysmCbriAm4Y0X9FLj58MNMu8/NKDZlCDj5Tr3NjWSp+W2q+G2QbftIYiP2ZmYrnbkhwcvioOMoz5HhOmvrV8+Jx/JqSPoY2qj0BdXsMZRIQ0eIxkLxTtGapR7unUnuRUZU9iQuWGKxJJQlXJLCtNYdoewhgDaMlFF5n2nos1ANRx6SfhrIKHogP1Nd7QUcOMcEkasoxOabHnzwgYj27teZZxsLPMJNcM66M8OTzKsBHdL2qD9LZ+gDDruJsjo2UYRsxhpoYbVqhBnTN1Pcr9P3XwGg4RyDiO1I7XKScp45QCkH+pZ5mcp5kq3oy+eWWmcxHbJWmqJQWgC4C+3TU89xiWEsiaIU91xfyeVDih33XA05/H3WMO/tVieNjSUcAKvCuwkBs6DlUaqb/9RSiv7fMOLIBTo/TQz13dPmJqWMh0EsxqQeufi928XlxRD/IbWcC1llMQPUr/CWuE3bgv5lcsXvm5Kf2fgO3DjeOjKJ/67VM+xRDqSkx8eQt4d/9PSOCpS67FgoMo0c86w/suPqp0wRTp7+xmsexkjoeY1/+4Lq4tjeodTWYzVXKpq29plH3Bq64hSBZYfsAZLCUv7z7R/h8B+39Vf9s+PVQnAEeRmneeRjjY5see14PWnwETXLPYLiexHQ="
matrix:
  include:
    - jdk: openjdk8
    #- jdk: openjdk9
    #- jdk: openjdk10
before_install:
  - docker version
  - docker info
install:
    - npm install newman
before_script:
    - node --version
    - npm --version
    - node_modules/.bin/newman --version     
script:
  - mvn clean install dockerfile:build
  - docker run --name example_api -d -t -p 127.0.0.1:8080:8080 alogo53/swagger-spring-example:1.0.0
  - docker ps
  - count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080); do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break; fi; done
  - docker logs example_api
  - node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json

after_success:
  - echo $TEST_SECRET_VAR
  - printenv
  #- docker login -u $DOCKER_USER -p $DOCKER_PASS
  #- docker tag alogo53/swagger-spring-example:1.0.0 alogo53/swagger-spring-example:1.0.0
  #- docker push alogo53/swagger-spring-example:1.0.0
  
  
#after_script:
    #- curl -v 127.0.0.1:8080
    #- curl -v localhost:8080
    #- docker ps
