sudo: required

services:
  - docker

language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    #- jdk: openjdk11


before_install:
  - docker version
  - docker info

script:
  - mvn clean install dockerfile:build
  - docker run -d -t -p 8080:8080 alogo53/swagger-spring:1.0.0
  - 
