sudo: required
services:
- docker
language: java
matrix:
  include:
  - jdk: openjdk8
before_install:
- docker version
- docker info
install:
- npm install newman
before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version
script:
- mvn clean install dockerfile:build
- docker run --name example_api -d -t -p 127.0.0.1:8080:8080 alogo53/swagger-spring-example:1.0.0
- docker ps
- count=0 && until $(curl --output /dev/null --silent --head --fail http://localhost:8080);
  do printf '.' && sleep 3 && count=$((count+1)) && if [ $count -gt 5 ]; then break;
  fi; done
- docker logs example_api
- node_modules/.bin/newman run tests/postman_collection.json -e tests/postman_environment.json
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- docker tag alogo53/swagger-spring-example:1.0.0 alogo53/swagger-spring-example:1.0.0
- docker push alogo53/swagger-spring-example:1.0.0
env:
  global:
  - secure: LSIrxEUM8Y3By8fKkNoxJxYArrrqsj1HC9Qbsbm/P6OclI1NIds+u7SrDtXhVg/KyxAZuFghjBPNFZGYcI65lJPtjcYBXzWPUcU6lJr+eGrvx4UpNeZtFBFCx33tH/dg468BN0p6Vnr5tqS9aAbFJcBCPnUlgCXXBc8hCzoE0JxgXiawm0oBNamBPgJrleoNLN6kYV0xLxJBMZgBGoDs619i1eo8+h9a/uN0VKXudnIRAZlpLFiOvppRW06gK1/X+7DoHaAY0d9t/O28E45rTH8LAjySZ/NPDH8FsXKJLSrSLyhbJZjI7I2n5INKEVUkHLpHFcNaAs+MUjUqvtsifz8yFQUnJq8zeePLunao88lgqg6sa00hwvs7zWxH15ZJVBKlJzHnqa6kSw7DHOz/p+bvi5QwTaOf5R7CXCJi1uJDcdRY+6RYYi8LL3q4gCM1+miwQOCtOXdgqTaGuxva1w+Da2id9s1YhEKc/Km964iy+4Uh4r1qq39lbasjhh8hIlp5Fqe+x1h8p8oP48Bk7dfznJ7M3Tnlz6EIVhExp4x9ZIeYzR+Q6UHOZ+jCsjkhPpPOkKhWBL1ipLeGpGT7V3lHS1diHZcBz3troquBROB1vpQWepAp28IUFkuZOM3Vv2FiD4DpUJZ4uz45FPSZsP/cHHXkXUwlj671OvrVYQc=
  - secure: F4VmWzoHNx2wFbig7USeDlcpD60KUyf4SZT0+43L7PEdO4zKT9hp6YOk37VZIgyHbRyTWkkE/vV8RD/u+ViFzxPTCwubs8GLg9AD9nAoiJXUN6Sqj+AIkINa/3FT1XWnlFzUSuO4R62YEKng+wBfow9ZzP/5ehV6JrWt+3YHrn4/1agRwRyWG3WMnzGg2cN+nxvMoDupwzXl/haDwzR1e7F0utm9GlH7anVpxjrfWnTVYmODrxzD+exaThIgyX1mLfpV0vMFP6tJVsWFk716/mFsHS7ppNkatHLpuHfGrH7LdD5sRFYOgjJ4/8KpMuBjSzORatKBj9AArIq4Mjgwz1ss6fjQZimqI939ix7wJadvnNPuzFlOk5DYvdikfRlNAyARADE6ywDP9RTPiqBdrzRoxBRo0q28grgrmMD5QMhFmZJ71B5QEqHOg5DWSd4EJB9l9KXgrtBUWGbAFxNicYaV4bBOhhMv5or2pDUMcUfAM1xYeJIw5PPFwq2Q78y8aUo5bHxNrnCq77f+rseU48ITtxQFEGTnU8UmcqYPoOoc8kcajbemTjP+WB8IHQRmNS8FPTttTEgq9fOxksmO9nLa7d30dH0DI1RZrnE+AINTnddAKNoasq6rgBYnYCHf3gP9Oe5UzLkGwBcBmggTvXtAj0GoVeRggupSrv0UsHk=
