sudo: required

services:
  - docker

language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11


before_install:
  # troubleshooting info in case of problems
  - docker version
  - docker info

script: mvn clean verify -B
